# Generated by Django 2.2.5 on 2019-09-08 02:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=20)),
                ('url', models.URLField(max_length=250)),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
